(setq-default evil-escape-key-sequence "jk")
(setq-default evil-escape-delay 0.2)
(setq-default indent-tabs-mode nil)
(setq-default tab-width 4)
;;(setq indent-line-function 'insert-tab)
(setq auto-save-default nil)
(setq c-basic-offset 4)
(setq evil-want-fine-undo t)
(setq byte-compile-warnings '(cl-functions))
(setq inhibit-compacting-font-caches t)
(setq projectile-enable-caching t) 
(setq spacemacs-show-trailing-whitespace nil)

(define-key evil-insert-state-map (kbd "C-y") #'yank)
(define-key evil-insert-state-map (kbd "M-w") #'kill-ring-save)

